package org.quickping.app.vpn

import org.json.JSONArray
import org.json.JSONObject
import org.quickping.app.model.DnsProvider

/**
 * Builds an explicit two-stage DNS policy for Android:
 *
 * 1. Android/local DNS is available only as a bootstrap resolver for the
 *    selected VPN node hostname.
 * 2. Application DNS is always sent to a secure DoH resolver through the
 *    selected proxy outbound.
 *
 * This prevents a healthy-looking VPN from leaking or depending on the ISP
 * resolver while still avoiding the circular dependency of trying to resolve
 * the proxy server through a DNS connection that itself needs that proxy.
 */
internal fun applyProviderDnsPolicy(
    @Suppress("UNUSED_PARAMETER") rawConfigJson: String,
    compiledConfigJson: String,
    provider: DnsProvider,
): String = runCatching {
    val config = JSONObject(compiledConfigJson)
    val route = config.optJSONObject("route") ?: return compiledConfigJson
    val proxyOutbound = route.optString("final").takeIf(String::isNotBlank)
        ?: return compiledConfigJson

    val endpoint = when (provider) {
        DnsProvider.Google -> DnsEndpoint("8.8.8.8", "dns.google")
        DnsProvider.Cloudflare,
        DnsProvider.Default,
        -> DnsEndpoint("1.1.1.1", "cloudflare-dns.com")
    }

    val localBootstrap = JSONObject()
        .put("type", "local")
        .put("tag", NODE_BOOTSTRAP_DNS_TAG)

    val tunnelDns = JSONObject()
        .put("type", "https")
        .put("tag", TUNNEL_DNS_TAG)
        .put("server", endpoint.address)
        .put("server_port", 443)
        .put("path", "/dns-query")
        .put("detour", proxyOutbound)
        .put(
            "tls",
            JSONObject()
                .put("enabled", true)
                .put("server_name", endpoint.serverName),
        )

    config.put(
        "dns",
        JSONObject()
            .put("servers", JSONArray().put(localBootstrap).put(tunnelDns))
            .put("final", TUNNEL_DNS_TAG)
            .put("strategy", "ipv4_only")
            .put("independent_cache", true),
    )

    // The physical resolver is intentionally scoped to resolving the VPN
    // server hostname. All DNS generated by applications is hijacked by the
    // route rules and uses TUNNEL_DNS_TAG instead.
    route.put(
        "default_domain_resolver",
        JSONObject()
            .put("server", NODE_BOOTSTRAP_DNS_TAG)
            .put("strategy", "ipv4_only"),
    )
    config.put("route", route)
    config.toString()
}.getOrDefault(compiledConfigJson)

private data class DnsEndpoint(val address: String, val serverName: String)

private const val NODE_BOOTSTRAP_DNS_TAG = "quickping-node-bootstrap"
private const val TUNNEL_DNS_TAG = "quickping-tunnel-doh"
